/* Copyright (c) Elliot Nunn */
/* Licensed under the MIT license */

#include <stdbool.h>
#include <stdio.h>
#include <string.h>

#include <Devices.h>
#include <Files.h>

#include "constnames.h"
#include "scratch.h"
#include "tap.h"

void testWrite(void) {
	puts("# Testing Write");

	struct line {
		int filesize, initialpos, mode, delta, writesize, finalpos, err;
		char data[12];
	};

	struct line lines[] = {
		{.filesize=0, .initialpos=0, .mode=fsAtMark, .delta=3, .writesize=0, .data="", .finalpos=0, .err=noErr},
		{.filesize=0, .initialpos=0, .mode=fsAtMark, .delta=3, .writesize=1, .data="A", .finalpos=1, .err=noErr},
		{.filesize=0, .initialpos=0, .mode=fsAtMark, .delta=3, .writesize=2, .data="AB", .finalpos=2, .err=noErr},
		{.filesize=0, .initialpos=0, .mode=fsAtMark, .delta=3, .writesize=3, .data="ABC", .finalpos=3, .err=noErr},
		{.filesize=0, .initialpos=0, .mode=fsAtMark, .delta=3, .writesize=4, .data="ABCD", .finalpos=4, .err=noErr},
		{.filesize=0, .initialpos=0, .mode=fsAtMark, .delta=3, .writesize=5, .data="ABCDE", .finalpos=5, .err=noErr},
		{.filesize=1, .initialpos=0, .mode=fsAtMark, .delta=3, .writesize=0, .data="a", .finalpos=0, .err=noErr},
		{.filesize=1, .initialpos=0, .mode=fsAtMark, .delta=3, .writesize=1, .data="A", .finalpos=1, .err=noErr},
		{.filesize=1, .initialpos=0, .mode=fsAtMark, .delta=3, .writesize=2, .data="AB", .finalpos=2, .err=noErr},
		{.filesize=1, .initialpos=0, .mode=fsAtMark, .delta=3, .writesize=3, .data="ABC", .finalpos=3, .err=noErr},
		{.filesize=1, .initialpos=0, .mode=fsAtMark, .delta=3, .writesize=4, .data="ABCD", .finalpos=4, .err=noErr},
		{.filesize=1, .initialpos=0, .mode=fsAtMark, .delta=3, .writesize=5, .data="ABCDE", .finalpos=5, .err=noErr},
		{.filesize=1, .initialpos=1, .mode=fsAtMark, .delta=3, .writesize=0, .data="a", .finalpos=1, .err=noErr},
		{.filesize=1, .initialpos=1, .mode=fsAtMark, .delta=3, .writesize=1, .data="aA", .finalpos=2, .err=noErr},
		{.filesize=1, .initialpos=1, .mode=fsAtMark, .delta=3, .writesize=2, .data="aAB", .finalpos=3, .err=noErr},
		{.filesize=1, .initialpos=1, .mode=fsAtMark, .delta=3, .writesize=3, .data="aABC", .finalpos=4, .err=noErr},
		{.filesize=1, .initialpos=1, .mode=fsAtMark, .delta=3, .writesize=4, .data="aABCD", .finalpos=5, .err=noErr},
		{.filesize=1, .initialpos=1, .mode=fsAtMark, .delta=3, .writesize=5, .data="aABCDE", .finalpos=6, .err=noErr},
		{.filesize=2, .initialpos=0, .mode=fsAtMark, .delta=3, .writesize=0, .data="ab", .finalpos=0, .err=noErr},
		{.filesize=2, .initialpos=0, .mode=fsAtMark, .delta=3, .writesize=1, .data="Ab", .finalpos=1, .err=noErr},
		{.filesize=2, .initialpos=0, .mode=fsAtMark, .delta=3, .writesize=2, .data="AB", .finalpos=2, .err=noErr},
		{.filesize=2, .initialpos=0, .mode=fsAtMark, .delta=3, .writesize=3, .data="ABC", .finalpos=3, .err=noErr},
		{.filesize=2, .initialpos=0, .mode=fsAtMark, .delta=3, .writesize=4, .data="ABCD", .finalpos=4, .err=noErr},
		{.filesize=2, .initialpos=0, .mode=fsAtMark, .delta=3, .writesize=5, .data="ABCDE", .finalpos=5, .err=noErr},
		{.filesize=2, .initialpos=1, .mode=fsAtMark, .delta=3, .writesize=0, .data="ab", .finalpos=1, .err=noErr},
		{.filesize=2, .initialpos=1, .mode=fsAtMark, .delta=3, .writesize=1, .data="aA", .finalpos=2, .err=noErr},
		{.filesize=2, .initialpos=1, .mode=fsAtMark, .delta=3, .writesize=2, .data="aAB", .finalpos=3, .err=noErr},
		{.filesize=2, .initialpos=1, .mode=fsAtMark, .delta=3, .writesize=3, .data="aABC", .finalpos=4, .err=noErr},
		{.filesize=2, .initialpos=1, .mode=fsAtMark, .delta=3, .writesize=4, .data="aABCD", .finalpos=5, .err=noErr},
		{.filesize=2, .initialpos=1, .mode=fsAtMark, .delta=3, .writesize=5, .data="aABCDE", .finalpos=6, .err=noErr},
		{.filesize=2, .initialpos=2, .mode=fsAtMark, .delta=3, .writesize=0, .data="ab", .finalpos=2, .err=noErr},
		{.filesize=2, .initialpos=2, .mode=fsAtMark, .delta=3, .writesize=1, .data="abA", .finalpos=3, .err=noErr},
		{.filesize=2, .initialpos=2, .mode=fsAtMark, .delta=3, .writesize=2, .data="abAB", .finalpos=4, .err=noErr},
		{.filesize=2, .initialpos=2, .mode=fsAtMark, .delta=3, .writesize=3, .data="abABC", .finalpos=5, .err=noErr},
		{.filesize=2, .initialpos=2, .mode=fsAtMark, .delta=3, .writesize=4, .data="abABCD", .finalpos=6, .err=noErr},
		{.filesize=2, .initialpos=2, .mode=fsAtMark, .delta=3, .writesize=5, .data="abABCDE", .finalpos=7, .err=noErr},
		{.filesize=3, .initialpos=0, .mode=fsAtMark, .delta=3, .writesize=0, .data="abc", .finalpos=0, .err=noErr},
		{.filesize=3, .initialpos=0, .mode=fsAtMark, .delta=3, .writesize=1, .data="Abc", .finalpos=1, .err=noErr},
		{.filesize=3, .initialpos=0, .mode=fsAtMark, .delta=3, .writesize=2, .data="ABc", .finalpos=2, .err=noErr},
		{.filesize=3, .initialpos=0, .mode=fsAtMark, .delta=3, .writesize=3, .data="ABC", .finalpos=3, .err=noErr},
		{.filesize=3, .initialpos=0, .mode=fsAtMark, .delta=3, .writesize=4, .data="ABCD", .finalpos=4, .err=noErr},
		{.filesize=3, .initialpos=0, .mode=fsAtMark, .delta=3, .writesize=5, .data="ABCDE", .finalpos=5, .err=noErr},
		{.filesize=3, .initialpos=1, .mode=fsAtMark, .delta=3, .writesize=0, .data="abc", .finalpos=1, .err=noErr},
		{.filesize=3, .initialpos=1, .mode=fsAtMark, .delta=3, .writesize=1, .data="aAc", .finalpos=2, .err=noErr},
		{.filesize=3, .initialpos=1, .mode=fsAtMark, .delta=3, .writesize=2, .data="aAB", .finalpos=3, .err=noErr},
		{.filesize=3, .initialpos=1, .mode=fsAtMark, .delta=3, .writesize=3, .data="aABC", .finalpos=4, .err=noErr},
		{.filesize=3, .initialpos=1, .mode=fsAtMark, .delta=3, .writesize=4, .data="aABCD", .finalpos=5, .err=noErr},
		{.filesize=3, .initialpos=1, .mode=fsAtMark, .delta=3, .writesize=5, .data="aABCDE", .finalpos=6, .err=noErr},
		{.filesize=3, .initialpos=2, .mode=fsAtMark, .delta=3, .writesize=0, .data="abc", .finalpos=2, .err=noErr},
		{.filesize=3, .initialpos=2, .mode=fsAtMark, .delta=3, .writesize=1, .data="abA", .finalpos=3, .err=noErr},
		{.filesize=3, .initialpos=2, .mode=fsAtMark, .delta=3, .writesize=2, .data="abAB", .finalpos=4, .err=noErr},
		{.filesize=3, .initialpos=2, .mode=fsAtMark, .delta=3, .writesize=3, .data="abABC", .finalpos=5, .err=noErr},
		{.filesize=3, .initialpos=2, .mode=fsAtMark, .delta=3, .writesize=4, .data="abABCD", .finalpos=6, .err=noErr},
		{.filesize=3, .initialpos=2, .mode=fsAtMark, .delta=3, .writesize=5, .data="abABCDE", .finalpos=7, .err=noErr},
		{.filesize=3, .initialpos=3, .mode=fsAtMark, .delta=3, .writesize=0, .data="abc", .finalpos=3, .err=noErr},
		{.filesize=3, .initialpos=3, .mode=fsAtMark, .delta=3, .writesize=1, .data="abcA", .finalpos=4, .err=noErr},
		{.filesize=3, .initialpos=3, .mode=fsAtMark, .delta=3, .writesize=2, .data="abcAB", .finalpos=5, .err=noErr},
		{.filesize=3, .initialpos=3, .mode=fsAtMark, .delta=3, .writesize=3, .data="abcABC", .finalpos=6, .err=noErr},
		{.filesize=3, .initialpos=3, .mode=fsAtMark, .delta=3, .writesize=4, .data="abcABCD", .finalpos=7, .err=noErr},
		{.filesize=3, .initialpos=3, .mode=fsAtMark, .delta=3, .writesize=5, .data="abcABCDE", .finalpos=8, .err=noErr},
		{.filesize=4, .initialpos=0, .mode=fsAtMark, .delta=3, .writesize=0, .data="abcd", .finalpos=0, .err=noErr},
		{.filesize=4, .initialpos=0, .mode=fsAtMark, .delta=3, .writesize=1, .data="Abcd", .finalpos=1, .err=noErr},
		{.filesize=4, .initialpos=0, .mode=fsAtMark, .delta=3, .writesize=2, .data="ABcd", .finalpos=2, .err=noErr},
		{.filesize=4, .initialpos=0, .mode=fsAtMark, .delta=3, .writesize=3, .data="ABCd", .finalpos=3, .err=noErr},
		{.filesize=4, .initialpos=0, .mode=fsAtMark, .delta=3, .writesize=4, .data="ABCD", .finalpos=4, .err=noErr},
		{.filesize=4, .initialpos=0, .mode=fsAtMark, .delta=3, .writesize=5, .data="ABCDE", .finalpos=5, .err=noErr},
		{.filesize=4, .initialpos=1, .mode=fsAtMark, .delta=3, .writesize=0, .data="abcd", .finalpos=1, .err=noErr},
		{.filesize=4, .initialpos=1, .mode=fsAtMark, .delta=3, .writesize=1, .data="aAcd", .finalpos=2, .err=noErr},
		{.filesize=4, .initialpos=1, .mode=fsAtMark, .delta=3, .writesize=2, .data="aABd", .finalpos=3, .err=noErr},
		{.filesize=4, .initialpos=1, .mode=fsAtMark, .delta=3, .writesize=3, .data="aABC", .finalpos=4, .err=noErr},
		{.filesize=4, .initialpos=1, .mode=fsAtMark, .delta=3, .writesize=4, .data="aABCD", .finalpos=5, .err=noErr},
		{.filesize=4, .initialpos=1, .mode=fsAtMark, .delta=3, .writesize=5, .data="aABCDE", .finalpos=6, .err=noErr},
		{.filesize=4, .initialpos=2, .mode=fsAtMark, .delta=3, .writesize=0, .data="abcd", .finalpos=2, .err=noErr},
		{.filesize=4, .initialpos=2, .mode=fsAtMark, .delta=3, .writesize=1, .data="abAd", .finalpos=3, .err=noErr},
		{.filesize=4, .initialpos=2, .mode=fsAtMark, .delta=3, .writesize=2, .data="abAB", .finalpos=4, .err=noErr},
		{.filesize=4, .initialpos=2, .mode=fsAtMark, .delta=3, .writesize=3, .data="abABC", .finalpos=5, .err=noErr},
		{.filesize=4, .initialpos=2, .mode=fsAtMark, .delta=3, .writesize=4, .data="abABCD", .finalpos=6, .err=noErr},
		{.filesize=4, .initialpos=2, .mode=fsAtMark, .delta=3, .writesize=5, .data="abABCDE", .finalpos=7, .err=noErr},
		{.filesize=4, .initialpos=3, .mode=fsAtMark, .delta=3, .writesize=0, .data="abcd", .finalpos=3, .err=noErr},
		{.filesize=4, .initialpos=3, .mode=fsAtMark, .delta=3, .writesize=1, .data="abcA", .finalpos=4, .err=noErr},
		{.filesize=4, .initialpos=3, .mode=fsAtMark, .delta=3, .writesize=2, .data="abcAB", .finalpos=5, .err=noErr},
		{.filesize=4, .initialpos=3, .mode=fsAtMark, .delta=3, .writesize=3, .data="abcABC", .finalpos=6, .err=noErr},
		{.filesize=4, .initialpos=3, .mode=fsAtMark, .delta=3, .writesize=4, .data="abcABCD", .finalpos=7, .err=noErr},
		{.filesize=4, .initialpos=3, .mode=fsAtMark, .delta=3, .writesize=5, .data="abcABCDE", .finalpos=8, .err=noErr},
		{.filesize=4, .initialpos=4, .mode=fsAtMark, .delta=3, .writesize=0, .data="abcd", .finalpos=4, .err=noErr},
		{.filesize=4, .initialpos=4, .mode=fsAtMark, .delta=3, .writesize=1, .data="abcdA", .finalpos=5, .err=noErr},
		{.filesize=4, .initialpos=4, .mode=fsAtMark, .delta=3, .writesize=2, .data="abcdAB", .finalpos=6, .err=noErr},
		{.filesize=4, .initialpos=4, .mode=fsAtMark, .delta=3, .writesize=3, .data="abcdABC", .finalpos=7, .err=noErr},
		{.filesize=4, .initialpos=4, .mode=fsAtMark, .delta=3, .writesize=4, .data="abcdABCD", .finalpos=8, .err=noErr},
		{.filesize=4, .initialpos=4, .mode=fsAtMark, .delta=3, .writesize=5, .data="abcdABCDE", .finalpos=9, .err=noErr},
		{.filesize=3, .initialpos=3, .mode=fsFromStart, .delta=0, .writesize=0, .data="abc", .finalpos=0, .err=noErr},
		{.filesize=3, .initialpos=3, .mode=fsFromStart, .delta=0, .writesize=1, .data="Abc", .finalpos=1, .err=noErr},
		{.filesize=3, .initialpos=3, .mode=fsFromStart, .delta=0, .writesize=2, .data="ABc", .finalpos=2, .err=noErr},
		{.filesize=3, .initialpos=3, .mode=fsFromStart, .delta=0, .writesize=3, .data="ABC", .finalpos=3, .err=noErr},
		{.filesize=3, .initialpos=3, .mode=fsFromStart, .delta=0, .writesize=4, .data="ABCD", .finalpos=4, .err=noErr},
		{.filesize=3, .initialpos=3, .mode=fsFromStart, .delta=0, .writesize=5, .data="ABCDE", .finalpos=5, .err=noErr},
		{.filesize=3, .initialpos=3, .mode=fsFromStart, .delta=1, .writesize=0, .data="abc", .finalpos=1, .err=noErr},
		{.filesize=3, .initialpos=3, .mode=fsFromStart, .delta=1, .writesize=1, .data="aAc", .finalpos=2, .err=noErr},
		{.filesize=3, .initialpos=3, .mode=fsFromStart, .delta=1, .writesize=2, .data="aAB", .finalpos=3, .err=noErr},
		{.filesize=3, .initialpos=3, .mode=fsFromStart, .delta=1, .writesize=3, .data="aABC", .finalpos=4, .err=noErr},
		{.filesize=3, .initialpos=3, .mode=fsFromStart, .delta=1, .writesize=4, .data="aABCD", .finalpos=5, .err=noErr},
		{.filesize=3, .initialpos=3, .mode=fsFromStart, .delta=1, .writesize=5, .data="aABCDE", .finalpos=6, .err=noErr},
		{.filesize=3, .initialpos=3, .mode=fsFromStart, .delta=2, .writesize=0, .data="abc", .finalpos=2, .err=noErr},
		{.filesize=3, .initialpos=3, .mode=fsFromStart, .delta=2, .writesize=1, .data="abA", .finalpos=3, .err=noErr},
		{.filesize=3, .initialpos=3, .mode=fsFromStart, .delta=2, .writesize=2, .data="abAB", .finalpos=4, .err=noErr},
		{.filesize=3, .initialpos=3, .mode=fsFromStart, .delta=2, .writesize=3, .data="abABC", .finalpos=5, .err=noErr},
		{.filesize=3, .initialpos=3, .mode=fsFromStart, .delta=2, .writesize=4, .data="abABCD", .finalpos=6, .err=noErr},
		{.filesize=3, .initialpos=3, .mode=fsFromStart, .delta=2, .writesize=5, .data="abABCDE", .finalpos=7, .err=noErr},
		{.filesize=3, .initialpos=3, .mode=fsFromStart, .delta=3, .writesize=0, .data="abc", .finalpos=3, .err=noErr},
		{.filesize=3, .initialpos=3, .mode=fsFromStart, .delta=3, .writesize=1, .data="abcA", .finalpos=4, .err=noErr},
		{.filesize=3, .initialpos=3, .mode=fsFromStart, .delta=3, .writesize=2, .data="abcAB", .finalpos=5, .err=noErr},
		{.filesize=3, .initialpos=3, .mode=fsFromStart, .delta=3, .writesize=3, .data="abcABC", .finalpos=6, .err=noErr},
		{.filesize=3, .initialpos=3, .mode=fsFromStart, .delta=3, .writesize=4, .data="abcABCD", .finalpos=7, .err=noErr},
		{.filesize=3, .initialpos=3, .mode=fsFromStart, .delta=3, .writesize=5, .data="abcABCDE", .finalpos=8, .err=noErr},
		{.filesize=4, .initialpos=3, .mode=fsFromStart, .delta=0, .writesize=0, .data="abcd", .finalpos=0, .err=noErr},
		{.filesize=4, .initialpos=3, .mode=fsFromStart, .delta=0, .writesize=1, .data="Abcd", .finalpos=1, .err=noErr},
		{.filesize=4, .initialpos=3, .mode=fsFromStart, .delta=0, .writesize=2, .data="ABcd", .finalpos=2, .err=noErr},
		{.filesize=4, .initialpos=3, .mode=fsFromStart, .delta=0, .writesize=3, .data="ABCd", .finalpos=3, .err=noErr},
		{.filesize=4, .initialpos=3, .mode=fsFromStart, .delta=0, .writesize=4, .data="ABCD", .finalpos=4, .err=noErr},
		{.filesize=4, .initialpos=3, .mode=fsFromStart, .delta=0, .writesize=5, .data="ABCDE", .finalpos=5, .err=noErr},
		{.filesize=4, .initialpos=3, .mode=fsFromStart, .delta=1, .writesize=0, .data="abcd", .finalpos=1, .err=noErr},
		{.filesize=4, .initialpos=3, .mode=fsFromStart, .delta=1, .writesize=1, .data="aAcd", .finalpos=2, .err=noErr},
		{.filesize=4, .initialpos=3, .mode=fsFromStart, .delta=1, .writesize=2, .data="aABd", .finalpos=3, .err=noErr},
		{.filesize=4, .initialpos=3, .mode=fsFromStart, .delta=1, .writesize=3, .data="aABC", .finalpos=4, .err=noErr},
		{.filesize=4, .initialpos=3, .mode=fsFromStart, .delta=1, .writesize=4, .data="aABCD", .finalpos=5, .err=noErr},
		{.filesize=4, .initialpos=3, .mode=fsFromStart, .delta=1, .writesize=5, .data="aABCDE", .finalpos=6, .err=noErr},
		{.filesize=4, .initialpos=3, .mode=fsFromStart, .delta=2, .writesize=0, .data="abcd", .finalpos=2, .err=noErr},
		{.filesize=4, .initialpos=3, .mode=fsFromStart, .delta=2, .writesize=1, .data="abAd", .finalpos=3, .err=noErr},
		{.filesize=4, .initialpos=3, .mode=fsFromStart, .delta=2, .writesize=2, .data="abAB", .finalpos=4, .err=noErr},
		{.filesize=4, .initialpos=3, .mode=fsFromStart, .delta=2, .writesize=3, .data="abABC", .finalpos=5, .err=noErr},
		{.filesize=4, .initialpos=3, .mode=fsFromStart, .delta=2, .writesize=4, .data="abABCD", .finalpos=6, .err=noErr},
		{.filesize=4, .initialpos=3, .mode=fsFromStart, .delta=2, .writesize=5, .data="abABCDE", .finalpos=7, .err=noErr},
		{.filesize=4, .initialpos=3, .mode=fsFromStart, .delta=3, .writesize=0, .data="abcd", .finalpos=3, .err=noErr},
		{.filesize=4, .initialpos=3, .mode=fsFromStart, .delta=3, .writesize=1, .data="abcA", .finalpos=4, .err=noErr},
		{.filesize=4, .initialpos=3, .mode=fsFromStart, .delta=3, .writesize=2, .data="abcAB", .finalpos=5, .err=noErr},
		{.filesize=4, .initialpos=3, .mode=fsFromStart, .delta=3, .writesize=3, .data="abcABC", .finalpos=6, .err=noErr},
		{.filesize=4, .initialpos=3, .mode=fsFromStart, .delta=3, .writesize=4, .data="abcABCD", .finalpos=7, .err=noErr},
		{.filesize=4, .initialpos=3, .mode=fsFromStart, .delta=3, .writesize=5, .data="abcABCDE", .finalpos=8, .err=noErr},
		{.filesize=4, .initialpos=3, .mode=fsFromStart, .delta=4, .writesize=0, .data="abcd", .finalpos=4, .err=noErr},
		{.filesize=4, .initialpos=3, .mode=fsFromStart, .delta=4, .writesize=1, .data="abcdA", .finalpos=5, .err=noErr},
		{.filesize=4, .initialpos=3, .mode=fsFromStart, .delta=4, .writesize=2, .data="abcdAB", .finalpos=6, .err=noErr},
		{.filesize=4, .initialpos=3, .mode=fsFromStart, .delta=4, .writesize=3, .data="abcdABC", .finalpos=7, .err=noErr},
		{.filesize=4, .initialpos=3, .mode=fsFromStart, .delta=4, .writesize=4, .data="abcdABCD", .finalpos=8, .err=noErr},
		{.filesize=4, .initialpos=3, .mode=fsFromStart, .delta=4, .writesize=5, .data="abcdABCDE", .finalpos=9, .err=noErr},
		{.filesize=3, .initialpos=3, .mode=fsFromLEOF, .delta=-3, .writesize=0, .data="abc", .finalpos=0, .err=noErr},
		{.filesize=3, .initialpos=3, .mode=fsFromLEOF, .delta=-3, .writesize=1, .data="Abc", .finalpos=1, .err=noErr},
		{.filesize=3, .initialpos=3, .mode=fsFromLEOF, .delta=-3, .writesize=2, .data="ABc", .finalpos=2, .err=noErr},
		{.filesize=3, .initialpos=3, .mode=fsFromLEOF, .delta=-3, .writesize=3, .data="ABC", .finalpos=3, .err=noErr},
		{.filesize=3, .initialpos=3, .mode=fsFromLEOF, .delta=-3, .writesize=4, .data="ABCD", .finalpos=4, .err=noErr},
		{.filesize=3, .initialpos=3, .mode=fsFromLEOF, .delta=-3, .writesize=5, .data="ABCDE", .finalpos=5, .err=noErr},
		{.filesize=3, .initialpos=3, .mode=fsFromLEOF, .delta=-2, .writesize=0, .data="abc", .finalpos=1, .err=noErr},
		{.filesize=3, .initialpos=3, .mode=fsFromLEOF, .delta=-2, .writesize=1, .data="aAc", .finalpos=2, .err=noErr},
		{.filesize=3, .initialpos=3, .mode=fsFromLEOF, .delta=-2, .writesize=2, .data="aAB", .finalpos=3, .err=noErr},
		{.filesize=3, .initialpos=3, .mode=fsFromLEOF, .delta=-2, .writesize=3, .data="aABC", .finalpos=4, .err=noErr},
		{.filesize=3, .initialpos=3, .mode=fsFromLEOF, .delta=-2, .writesize=4, .data="aABCD", .finalpos=5, .err=noErr},
		{.filesize=3, .initialpos=3, .mode=fsFromLEOF, .delta=-2, .writesize=5, .data="aABCDE", .finalpos=6, .err=noErr},
		{.filesize=3, .initialpos=3, .mode=fsFromLEOF, .delta=-1, .writesize=0, .data="abc", .finalpos=2, .err=noErr},
		{.filesize=3, .initialpos=3, .mode=fsFromLEOF, .delta=-1, .writesize=1, .data="abA", .finalpos=3, .err=noErr},
		{.filesize=3, .initialpos=3, .mode=fsFromLEOF, .delta=-1, .writesize=2, .data="abAB", .finalpos=4, .err=noErr},
		{.filesize=3, .initialpos=3, .mode=fsFromLEOF, .delta=-1, .writesize=3, .data="abABC", .finalpos=5, .err=noErr},
		{.filesize=3, .initialpos=3, .mode=fsFromLEOF, .delta=-1, .writesize=4, .data="abABCD", .finalpos=6, .err=noErr},
		{.filesize=3, .initialpos=3, .mode=fsFromLEOF, .delta=-1, .writesize=5, .data="abABCDE", .finalpos=7, .err=noErr},
		{.filesize=3, .initialpos=3, .mode=fsFromLEOF, .delta=0, .writesize=0, .data="abc", .finalpos=3, .err=noErr},
		{.filesize=3, .initialpos=3, .mode=fsFromLEOF, .delta=0, .writesize=1, .data="abcA", .finalpos=4, .err=noErr},
		{.filesize=3, .initialpos=3, .mode=fsFromLEOF, .delta=0, .writesize=2, .data="abcAB", .finalpos=5, .err=noErr},
		{.filesize=3, .initialpos=3, .mode=fsFromLEOF, .delta=0, .writesize=3, .data="abcABC", .finalpos=6, .err=noErr},
		{.filesize=3, .initialpos=3, .mode=fsFromLEOF, .delta=0, .writesize=4, .data="abcABCD", .finalpos=7, .err=noErr},
		{.filesize=3, .initialpos=3, .mode=fsFromLEOF, .delta=0, .writesize=5, .data="abcABCDE", .finalpos=8, .err=noErr},
		{.filesize=4, .initialpos=3, .mode=fsFromLEOF, .delta=-4, .writesize=0, .data="abcd", .finalpos=0, .err=noErr},
		{.filesize=4, .initialpos=3, .mode=fsFromLEOF, .delta=-4, .writesize=1, .data="Abcd", .finalpos=1, .err=noErr},
		{.filesize=4, .initialpos=3, .mode=fsFromLEOF, .delta=-4, .writesize=2, .data="ABcd", .finalpos=2, .err=noErr},
		{.filesize=4, .initialpos=3, .mode=fsFromLEOF, .delta=-4, .writesize=3, .data="ABCd", .finalpos=3, .err=noErr},
		{.filesize=4, .initialpos=3, .mode=fsFromLEOF, .delta=-4, .writesize=4, .data="ABCD", .finalpos=4, .err=noErr},
		{.filesize=4, .initialpos=3, .mode=fsFromLEOF, .delta=-4, .writesize=5, .data="ABCDE", .finalpos=5, .err=noErr},
		{.filesize=4, .initialpos=3, .mode=fsFromLEOF, .delta=-3, .writesize=0, .data="abcd", .finalpos=1, .err=noErr},
		{.filesize=4, .initialpos=3, .mode=fsFromLEOF, .delta=-3, .writesize=1, .data="aAcd", .finalpos=2, .err=noErr},
		{.filesize=4, .initialpos=3, .mode=fsFromLEOF, .delta=-3, .writesize=2, .data="aABd", .finalpos=3, .err=noErr},
		{.filesize=4, .initialpos=3, .mode=fsFromLEOF, .delta=-3, .writesize=3, .data="aABC", .finalpos=4, .err=noErr},
		{.filesize=4, .initialpos=3, .mode=fsFromLEOF, .delta=-3, .writesize=4, .data="aABCD", .finalpos=5, .err=noErr},
		{.filesize=4, .initialpos=3, .mode=fsFromLEOF, .delta=-3, .writesize=5, .data="aABCDE", .finalpos=6, .err=noErr},
		{.filesize=4, .initialpos=3, .mode=fsFromLEOF, .delta=-2, .writesize=0, .data="abcd", .finalpos=2, .err=noErr},
		{.filesize=4, .initialpos=3, .mode=fsFromLEOF, .delta=-2, .writesize=1, .data="abAd", .finalpos=3, .err=noErr},
		{.filesize=4, .initialpos=3, .mode=fsFromLEOF, .delta=-2, .writesize=2, .data="abAB", .finalpos=4, .err=noErr},
		{.filesize=4, .initialpos=3, .mode=fsFromLEOF, .delta=-2, .writesize=3, .data="abABC", .finalpos=5, .err=noErr},
		{.filesize=4, .initialpos=3, .mode=fsFromLEOF, .delta=-2, .writesize=4, .data="abABCD", .finalpos=6, .err=noErr},
		{.filesize=4, .initialpos=3, .mode=fsFromLEOF, .delta=-2, .writesize=5, .data="abABCDE", .finalpos=7, .err=noErr},
		{.filesize=4, .initialpos=3, .mode=fsFromLEOF, .delta=-1, .writesize=0, .data="abcd", .finalpos=3, .err=noErr},
		{.filesize=4, .initialpos=3, .mode=fsFromLEOF, .delta=-1, .writesize=1, .data="abcA", .finalpos=4, .err=noErr},
		{.filesize=4, .initialpos=3, .mode=fsFromLEOF, .delta=-1, .writesize=2, .data="abcAB", .finalpos=5, .err=noErr},
		{.filesize=4, .initialpos=3, .mode=fsFromLEOF, .delta=-1, .writesize=3, .data="abcABC", .finalpos=6, .err=noErr},
		{.filesize=4, .initialpos=3, .mode=fsFromLEOF, .delta=-1, .writesize=4, .data="abcABCD", .finalpos=7, .err=noErr},
		{.filesize=4, .initialpos=3, .mode=fsFromLEOF, .delta=-1, .writesize=5, .data="abcABCDE", .finalpos=8, .err=noErr},
		{.filesize=4, .initialpos=3, .mode=fsFromLEOF, .delta=0, .writesize=0, .data="abcd", .finalpos=4, .err=noErr},
		{.filesize=4, .initialpos=3, .mode=fsFromLEOF, .delta=0, .writesize=1, .data="abcdA", .finalpos=5, .err=noErr},
		{.filesize=4, .initialpos=3, .mode=fsFromLEOF, .delta=0, .writesize=2, .data="abcdAB", .finalpos=6, .err=noErr},
		{.filesize=4, .initialpos=3, .mode=fsFromLEOF, .delta=0, .writesize=3, .data="abcdABC", .finalpos=7, .err=noErr},
		{.filesize=4, .initialpos=3, .mode=fsFromLEOF, .delta=0, .writesize=4, .data="abcdABCD", .finalpos=8, .err=noErr},
		{.filesize=4, .initialpos=3, .mode=fsFromLEOF, .delta=0, .writesize=5, .data="abcdABCDE", .finalpos=9, .err=noErr},
		{.filesize=0, .initialpos=0, .mode=fsFromMark, .delta=0, .writesize=0, .data="", .finalpos=0, .err=noErr},
		{.filesize=0, .initialpos=0, .mode=fsFromMark, .delta=0, .writesize=1, .data="A", .finalpos=1, .err=noErr},
		{.filesize=0, .initialpos=0, .mode=fsFromMark, .delta=0, .writesize=2, .data="AB", .finalpos=2, .err=noErr},
		{.filesize=0, .initialpos=0, .mode=fsFromMark, .delta=0, .writesize=3, .data="ABC", .finalpos=3, .err=noErr},
		{.filesize=0, .initialpos=0, .mode=fsFromMark, .delta=0, .writesize=4, .data="ABCD", .finalpos=4, .err=noErr},
		{.filesize=0, .initialpos=0, .mode=fsFromMark, .delta=0, .writesize=5, .data="ABCDE", .finalpos=5, .err=noErr},
		{.filesize=1, .initialpos=0, .mode=fsFromMark, .delta=0, .writesize=0, .data="a", .finalpos=0, .err=noErr},
		{.filesize=1, .initialpos=0, .mode=fsFromMark, .delta=0, .writesize=1, .data="A", .finalpos=1, .err=noErr},
		{.filesize=1, .initialpos=0, .mode=fsFromMark, .delta=0, .writesize=2, .data="AB", .finalpos=2, .err=noErr},
		{.filesize=1, .initialpos=0, .mode=fsFromMark, .delta=0, .writesize=3, .data="ABC", .finalpos=3, .err=noErr},
		{.filesize=1, .initialpos=0, .mode=fsFromMark, .delta=0, .writesize=4, .data="ABCD", .finalpos=4, .err=noErr},
		{.filesize=1, .initialpos=0, .mode=fsFromMark, .delta=0, .writesize=5, .data="ABCDE", .finalpos=5, .err=noErr},
		{.filesize=1, .initialpos=0, .mode=fsFromMark, .delta=1, .writesize=0, .data="a", .finalpos=1, .err=noErr},
		{.filesize=1, .initialpos=0, .mode=fsFromMark, .delta=1, .writesize=1, .data="aA", .finalpos=2, .err=noErr},
		{.filesize=1, .initialpos=0, .mode=fsFromMark, .delta=1, .writesize=2, .data="aAB", .finalpos=3, .err=noErr},
		{.filesize=1, .initialpos=0, .mode=fsFromMark, .delta=1, .writesize=3, .data="aABC", .finalpos=4, .err=noErr},
		{.filesize=1, .initialpos=0, .mode=fsFromMark, .delta=1, .writesize=4, .data="aABCD", .finalpos=5, .err=noErr},
		{.filesize=1, .initialpos=0, .mode=fsFromMark, .delta=1, .writesize=5, .data="aABCDE", .finalpos=6, .err=noErr},
		{.filesize=1, .initialpos=1, .mode=fsFromMark, .delta=-1, .writesize=0, .data="a", .finalpos=0, .err=noErr},
		{.filesize=1, .initialpos=1, .mode=fsFromMark, .delta=-1, .writesize=1, .data="A", .finalpos=1, .err=noErr},
		{.filesize=1, .initialpos=1, .mode=fsFromMark, .delta=-1, .writesize=2, .data="AB", .finalpos=2, .err=noErr},
		{.filesize=1, .initialpos=1, .mode=fsFromMark, .delta=-1, .writesize=3, .data="ABC", .finalpos=3, .err=noErr},
		{.filesize=1, .initialpos=1, .mode=fsFromMark, .delta=-1, .writesize=4, .data="ABCD", .finalpos=4, .err=noErr},
		{.filesize=1, .initialpos=1, .mode=fsFromMark, .delta=-1, .writesize=5, .data="ABCDE", .finalpos=5, .err=noErr},
		{.filesize=1, .initialpos=1, .mode=fsFromMark, .delta=0, .writesize=0, .data="a", .finalpos=1, .err=noErr},
		{.filesize=1, .initialpos=1, .mode=fsFromMark, .delta=0, .writesize=1, .data="aA", .finalpos=2, .err=noErr},
		{.filesize=1, .initialpos=1, .mode=fsFromMark, .delta=0, .writesize=2, .data="aAB", .finalpos=3, .err=noErr},
		{.filesize=1, .initialpos=1, .mode=fsFromMark, .delta=0, .writesize=3, .data="aABC", .finalpos=4, .err=noErr},
		{.filesize=1, .initialpos=1, .mode=fsFromMark, .delta=0, .writesize=4, .data="aABCD", .finalpos=5, .err=noErr},
		{.filesize=1, .initialpos=1, .mode=fsFromMark, .delta=0, .writesize=5, .data="aABCDE", .finalpos=6, .err=noErr},
		{.filesize=2, .initialpos=0, .mode=fsFromMark, .delta=0, .writesize=0, .data="ab", .finalpos=0, .err=noErr},
		{.filesize=2, .initialpos=0, .mode=fsFromMark, .delta=0, .writesize=1, .data="Ab", .finalpos=1, .err=noErr},
		{.filesize=2, .initialpos=0, .mode=fsFromMark, .delta=0, .writesize=2, .data="AB", .finalpos=2, .err=noErr},
		{.filesize=2, .initialpos=0, .mode=fsFromMark, .delta=0, .writesize=3, .data="ABC", .finalpos=3, .err=noErr},
		{.filesize=2, .initialpos=0, .mode=fsFromMark, .delta=0, .writesize=4, .data="ABCD", .finalpos=4, .err=noErr},
		{.filesize=2, .initialpos=0, .mode=fsFromMark, .delta=0, .writesize=5, .data="ABCDE", .finalpos=5, .err=noErr},
		{.filesize=2, .initialpos=0, .mode=fsFromMark, .delta=1, .writesize=0, .data="ab", .finalpos=1, .err=noErr},
		{.filesize=2, .initialpos=0, .mode=fsFromMark, .delta=1, .writesize=1, .data="aA", .finalpos=2, .err=noErr},
		{.filesize=2, .initialpos=0, .mode=fsFromMark, .delta=1, .writesize=2, .data="aAB", .finalpos=3, .err=noErr},
		{.filesize=2, .initialpos=0, .mode=fsFromMark, .delta=1, .writesize=3, .data="aABC", .finalpos=4, .err=noErr},
		{.filesize=2, .initialpos=0, .mode=fsFromMark, .delta=1, .writesize=4, .data="aABCD", .finalpos=5, .err=noErr},
		{.filesize=2, .initialpos=0, .mode=fsFromMark, .delta=1, .writesize=5, .data="aABCDE", .finalpos=6, .err=noErr},
		{.filesize=2, .initialpos=0, .mode=fsFromMark, .delta=2, .writesize=0, .data="ab", .finalpos=2, .err=noErr},
		{.filesize=2, .initialpos=0, .mode=fsFromMark, .delta=2, .writesize=1, .data="abA", .finalpos=3, .err=noErr},
		{.filesize=2, .initialpos=0, .mode=fsFromMark, .delta=2, .writesize=2, .data="abAB", .finalpos=4, .err=noErr},
		{.filesize=2, .initialpos=0, .mode=fsFromMark, .delta=2, .writesize=3, .data="abABC", .finalpos=5, .err=noErr},
		{.filesize=2, .initialpos=0, .mode=fsFromMark, .delta=2, .writesize=4, .data="abABCD", .finalpos=6, .err=noErr},
		{.filesize=2, .initialpos=0, .mode=fsFromMark, .delta=2, .writesize=5, .data="abABCDE", .finalpos=7, .err=noErr},
		{.filesize=2, .initialpos=1, .mode=fsFromMark, .delta=-1, .writesize=0, .data="ab", .finalpos=0, .err=noErr},
		{.filesize=2, .initialpos=1, .mode=fsFromMark, .delta=-1, .writesize=1, .data="Ab", .finalpos=1, .err=noErr},
		{.filesize=2, .initialpos=1, .mode=fsFromMark, .delta=-1, .writesize=2, .data="AB", .finalpos=2, .err=noErr},
		{.filesize=2, .initialpos=1, .mode=fsFromMark, .delta=-1, .writesize=3, .data="ABC", .finalpos=3, .err=noErr},
		{.filesize=2, .initialpos=1, .mode=fsFromMark, .delta=-1, .writesize=4, .data="ABCD", .finalpos=4, .err=noErr},
		{.filesize=2, .initialpos=1, .mode=fsFromMark, .delta=-1, .writesize=5, .data="ABCDE", .finalpos=5, .err=noErr},
		{.filesize=2, .initialpos=1, .mode=fsFromMark, .delta=0, .writesize=0, .data="ab", .finalpos=1, .err=noErr},
		{.filesize=2, .initialpos=1, .mode=fsFromMark, .delta=0, .writesize=1, .data="aA", .finalpos=2, .err=noErr},
		{.filesize=2, .initialpos=1, .mode=fsFromMark, .delta=0, .writesize=2, .data="aAB", .finalpos=3, .err=noErr},
		{.filesize=2, .initialpos=1, .mode=fsFromMark, .delta=0, .writesize=3, .data="aABC", .finalpos=4, .err=noErr},
		{.filesize=2, .initialpos=1, .mode=fsFromMark, .delta=0, .writesize=4, .data="aABCD", .finalpos=5, .err=noErr},
		{.filesize=2, .initialpos=1, .mode=fsFromMark, .delta=0, .writesize=5, .data="aABCDE", .finalpos=6, .err=noErr},
		{.filesize=2, .initialpos=1, .mode=fsFromMark, .delta=1, .writesize=0, .data="ab", .finalpos=2, .err=noErr},
		{.filesize=2, .initialpos=1, .mode=fsFromMark, .delta=1, .writesize=1, .data="abA", .finalpos=3, .err=noErr},
		{.filesize=2, .initialpos=1, .mode=fsFromMark, .delta=1, .writesize=2, .data="abAB", .finalpos=4, .err=noErr},
		{.filesize=2, .initialpos=1, .mode=fsFromMark, .delta=1, .writesize=3, .data="abABC", .finalpos=5, .err=noErr},
		{.filesize=2, .initialpos=1, .mode=fsFromMark, .delta=1, .writesize=4, .data="abABCD", .finalpos=6, .err=noErr},
		{.filesize=2, .initialpos=1, .mode=fsFromMark, .delta=1, .writesize=5, .data="abABCDE", .finalpos=7, .err=noErr},
		{.filesize=2, .initialpos=2, .mode=fsFromMark, .delta=-2, .writesize=0, .data="ab", .finalpos=0, .err=noErr},
		{.filesize=2, .initialpos=2, .mode=fsFromMark, .delta=-2, .writesize=1, .data="Ab", .finalpos=1, .err=noErr},
		{.filesize=2, .initialpos=2, .mode=fsFromMark, .delta=-2, .writesize=2, .data="AB", .finalpos=2, .err=noErr},
		{.filesize=2, .initialpos=2, .mode=fsFromMark, .delta=-2, .writesize=3, .data="ABC", .finalpos=3, .err=noErr},
		{.filesize=2, .initialpos=2, .mode=fsFromMark, .delta=-2, .writesize=4, .data="ABCD", .finalpos=4, .err=noErr},
		{.filesize=2, .initialpos=2, .mode=fsFromMark, .delta=-2, .writesize=5, .data="ABCDE", .finalpos=5, .err=noErr},
		{.filesize=2, .initialpos=2, .mode=fsFromMark, .delta=-1, .writesize=0, .data="ab", .finalpos=1, .err=noErr},
		{.filesize=2, .initialpos=2, .mode=fsFromMark, .delta=-1, .writesize=1, .data="aA", .finalpos=2, .err=noErr},
		{.filesize=2, .initialpos=2, .mode=fsFromMark, .delta=-1, .writesize=2, .data="aAB", .finalpos=3, .err=noErr},
		{.filesize=2, .initialpos=2, .mode=fsFromMark, .delta=-1, .writesize=3, .data="aABC", .finalpos=4, .err=noErr},
		{.filesize=2, .initialpos=2, .mode=fsFromMark, .delta=-1, .writesize=4, .data="aABCD", .finalpos=5, .err=noErr},
		{.filesize=2, .initialpos=2, .mode=fsFromMark, .delta=-1, .writesize=5, .data="aABCDE", .finalpos=6, .err=noErr},
		{.filesize=2, .initialpos=2, .mode=fsFromMark, .delta=0, .writesize=0, .data="ab", .finalpos=2, .err=noErr},
		{.filesize=2, .initialpos=2, .mode=fsFromMark, .delta=0, .writesize=1, .data="abA", .finalpos=3, .err=noErr},
		{.filesize=2, .initialpos=2, .mode=fsFromMark, .delta=0, .writesize=2, .data="abAB", .finalpos=4, .err=noErr},
		{.filesize=2, .initialpos=2, .mode=fsFromMark, .delta=0, .writesize=3, .data="abABC", .finalpos=5, .err=noErr},
		{.filesize=2, .initialpos=2, .mode=fsFromMark, .delta=0, .writesize=4, .data="abABCD", .finalpos=6, .err=noErr},
		{.filesize=2, .initialpos=2, .mode=fsFromMark, .delta=0, .writesize=5, .data="abABCDE", .finalpos=7, .err=noErr},
		{.filesize=3, .initialpos=0, .mode=fsFromMark, .delta=0, .writesize=0, .data="abc", .finalpos=0, .err=noErr},
		{.filesize=3, .initialpos=0, .mode=fsFromMark, .delta=0, .writesize=1, .data="Abc", .finalpos=1, .err=noErr},
		{.filesize=3, .initialpos=0, .mode=fsFromMark, .delta=0, .writesize=2, .data="ABc", .finalpos=2, .err=noErr},
		{.filesize=3, .initialpos=0, .mode=fsFromMark, .delta=0, .writesize=3, .data="ABC", .finalpos=3, .err=noErr},
		{.filesize=3, .initialpos=0, .mode=fsFromMark, .delta=0, .writesize=4, .data="ABCD", .finalpos=4, .err=noErr},
		{.filesize=3, .initialpos=0, .mode=fsFromMark, .delta=0, .writesize=5, .data="ABCDE", .finalpos=5, .err=noErr},
		{.filesize=3, .initialpos=0, .mode=fsFromMark, .delta=1, .writesize=0, .data="abc", .finalpos=1, .err=noErr},
		{.filesize=3, .initialpos=0, .mode=fsFromMark, .delta=1, .writesize=1, .data="aAc", .finalpos=2, .err=noErr},
		{.filesize=3, .initialpos=0, .mode=fsFromMark, .delta=1, .writesize=2, .data="aAB", .finalpos=3, .err=noErr},
		{.filesize=3, .initialpos=0, .mode=fsFromMark, .delta=1, .writesize=3, .data="aABC", .finalpos=4, .err=noErr},
		{.filesize=3, .initialpos=0, .mode=fsFromMark, .delta=1, .writesize=4, .data="aABCD", .finalpos=5, .err=noErr},
		{.filesize=3, .initialpos=0, .mode=fsFromMark, .delta=1, .writesize=5, .data="aABCDE", .finalpos=6, .err=noErr},
		{.filesize=3, .initialpos=0, .mode=fsFromMark, .delta=2, .writesize=0, .data="abc", .finalpos=2, .err=noErr},
		{.filesize=3, .initialpos=0, .mode=fsFromMark, .delta=2, .writesize=1, .data="abA", .finalpos=3, .err=noErr},
		{.filesize=3, .initialpos=0, .mode=fsFromMark, .delta=2, .writesize=2, .data="abAB", .finalpos=4, .err=noErr},
		{.filesize=3, .initialpos=0, .mode=fsFromMark, .delta=2, .writesize=3, .data="abABC", .finalpos=5, .err=noErr},
		{.filesize=3, .initialpos=0, .mode=fsFromMark, .delta=2, .writesize=4, .data="abABCD", .finalpos=6, .err=noErr},
		{.filesize=3, .initialpos=0, .mode=fsFromMark, .delta=2, .writesize=5, .data="abABCDE", .finalpos=7, .err=noErr},
		{.filesize=3, .initialpos=0, .mode=fsFromMark, .delta=3, .writesize=0, .data="abc", .finalpos=3, .err=noErr},
		{.filesize=3, .initialpos=0, .mode=fsFromMark, .delta=3, .writesize=1, .data="abcA", .finalpos=4, .err=noErr},
		{.filesize=3, .initialpos=0, .mode=fsFromMark, .delta=3, .writesize=2, .data="abcAB", .finalpos=5, .err=noErr},
		{.filesize=3, .initialpos=0, .mode=fsFromMark, .delta=3, .writesize=3, .data="abcABC", .finalpos=6, .err=noErr},
		{.filesize=3, .initialpos=0, .mode=fsFromMark, .delta=3, .writesize=4, .data="abcABCD", .finalpos=7, .err=noErr},
		{.filesize=3, .initialpos=0, .mode=fsFromMark, .delta=3, .writesize=5, .data="abcABCDE", .finalpos=8, .err=noErr},
		{.filesize=3, .initialpos=1, .mode=fsFromMark, .delta=-1, .writesize=0, .data="abc", .finalpos=0, .err=noErr},
		{.filesize=3, .initialpos=1, .mode=fsFromMark, .delta=-1, .writesize=1, .data="Abc", .finalpos=1, .err=noErr},
		{.filesize=3, .initialpos=1, .mode=fsFromMark, .delta=-1, .writesize=2, .data="ABc", .finalpos=2, .err=noErr},
		{.filesize=3, .initialpos=1, .mode=fsFromMark, .delta=-1, .writesize=3, .data="ABC", .finalpos=3, .err=noErr},
		{.filesize=3, .initialpos=1, .mode=fsFromMark, .delta=-1, .writesize=4, .data="ABCD", .finalpos=4, .err=noErr},
		{.filesize=3, .initialpos=1, .mode=fsFromMark, .delta=-1, .writesize=5, .data="ABCDE", .finalpos=5, .err=noErr},
		{.filesize=3, .initialpos=1, .mode=fsFromMark, .delta=0, .writesize=0, .data="abc", .finalpos=1, .err=noErr},
		{.filesize=3, .initialpos=1, .mode=fsFromMark, .delta=0, .writesize=1, .data="aAc", .finalpos=2, .err=noErr},
		{.filesize=3, .initialpos=1, .mode=fsFromMark, .delta=0, .writesize=2, .data="aAB", .finalpos=3, .err=noErr},
		{.filesize=3, .initialpos=1, .mode=fsFromMark, .delta=0, .writesize=3, .data="aABC", .finalpos=4, .err=noErr},
		{.filesize=3, .initialpos=1, .mode=fsFromMark, .delta=0, .writesize=4, .data="aABCD", .finalpos=5, .err=noErr},
		{.filesize=3, .initialpos=1, .mode=fsFromMark, .delta=0, .writesize=5, .data="aABCDE", .finalpos=6, .err=noErr},
		{.filesize=3, .initialpos=1, .mode=fsFromMark, .delta=1, .writesize=0, .data="abc", .finalpos=2, .err=noErr},
		{.filesize=3, .initialpos=1, .mode=fsFromMark, .delta=1, .writesize=1, .data="abA", .finalpos=3, .err=noErr},
		{.filesize=3, .initialpos=1, .mode=fsFromMark, .delta=1, .writesize=2, .data="abAB", .finalpos=4, .err=noErr},
		{.filesize=3, .initialpos=1, .mode=fsFromMark, .delta=1, .writesize=3, .data="abABC", .finalpos=5, .err=noErr},
		{.filesize=3, .initialpos=1, .mode=fsFromMark, .delta=1, .writesize=4, .data="abABCD", .finalpos=6, .err=noErr},
		{.filesize=3, .initialpos=1, .mode=fsFromMark, .delta=1, .writesize=5, .data="abABCDE", .finalpos=7, .err=noErr},
		{.filesize=3, .initialpos=1, .mode=fsFromMark, .delta=2, .writesize=0, .data="abc", .finalpos=3, .err=noErr},
		{.filesize=3, .initialpos=1, .mode=fsFromMark, .delta=2, .writesize=1, .data="abcA", .finalpos=4, .err=noErr},
		{.filesize=3, .initialpos=1, .mode=fsFromMark, .delta=2, .writesize=2, .data="abcAB", .finalpos=5, .err=noErr},
		{.filesize=3, .initialpos=1, .mode=fsFromMark, .delta=2, .writesize=3, .data="abcABC", .finalpos=6, .err=noErr},
		{.filesize=3, .initialpos=1, .mode=fsFromMark, .delta=2, .writesize=4, .data="abcABCD", .finalpos=7, .err=noErr},
		{.filesize=3, .initialpos=1, .mode=fsFromMark, .delta=2, .writesize=5, .data="abcABCDE", .finalpos=8, .err=noErr},
		{.filesize=3, .initialpos=2, .mode=fsFromMark, .delta=-2, .writesize=0, .data="abc", .finalpos=0, .err=noErr},
		{.filesize=3, .initialpos=2, .mode=fsFromMark, .delta=-2, .writesize=1, .data="Abc", .finalpos=1, .err=noErr},
		{.filesize=3, .initialpos=2, .mode=fsFromMark, .delta=-2, .writesize=2, .data="ABc", .finalpos=2, .err=noErr},
		{.filesize=3, .initialpos=2, .mode=fsFromMark, .delta=-2, .writesize=3, .data="ABC", .finalpos=3, .err=noErr},
		{.filesize=3, .initialpos=2, .mode=fsFromMark, .delta=-2, .writesize=4, .data="ABCD", .finalpos=4, .err=noErr},
		{.filesize=3, .initialpos=2, .mode=fsFromMark, .delta=-2, .writesize=5, .data="ABCDE", .finalpos=5, .err=noErr},
		{.filesize=3, .initialpos=2, .mode=fsFromMark, .delta=-1, .writesize=0, .data="abc", .finalpos=1, .err=noErr},
		{.filesize=3, .initialpos=2, .mode=fsFromMark, .delta=-1, .writesize=1, .data="aAc", .finalpos=2, .err=noErr},
		{.filesize=3, .initialpos=2, .mode=fsFromMark, .delta=-1, .writesize=2, .data="aAB", .finalpos=3, .err=noErr},
		{.filesize=3, .initialpos=2, .mode=fsFromMark, .delta=-1, .writesize=3, .data="aABC", .finalpos=4, .err=noErr},
		{.filesize=3, .initialpos=2, .mode=fsFromMark, .delta=-1, .writesize=4, .data="aABCD", .finalpos=5, .err=noErr},
		{.filesize=3, .initialpos=2, .mode=fsFromMark, .delta=-1, .writesize=5, .data="aABCDE", .finalpos=6, .err=noErr},
		{.filesize=3, .initialpos=2, .mode=fsFromMark, .delta=0, .writesize=0, .data="abc", .finalpos=2, .err=noErr},
		{.filesize=3, .initialpos=2, .mode=fsFromMark, .delta=0, .writesize=1, .data="abA", .finalpos=3, .err=noErr},
		{.filesize=3, .initialpos=2, .mode=fsFromMark, .delta=0, .writesize=2, .data="abAB", .finalpos=4, .err=noErr},
		{.filesize=3, .initialpos=2, .mode=fsFromMark, .delta=0, .writesize=3, .data="abABC", .finalpos=5, .err=noErr},
		{.filesize=3, .initialpos=2, .mode=fsFromMark, .delta=0, .writesize=4, .data="abABCD", .finalpos=6, .err=noErr},
		{.filesize=3, .initialpos=2, .mode=fsFromMark, .delta=0, .writesize=5, .data="abABCDE", .finalpos=7, .err=noErr},
		{.filesize=3, .initialpos=2, .mode=fsFromMark, .delta=1, .writesize=0, .data="abc", .finalpos=3, .err=noErr},
		{.filesize=3, .initialpos=2, .mode=fsFromMark, .delta=1, .writesize=1, .data="abcA", .finalpos=4, .err=noErr},
		{.filesize=3, .initialpos=2, .mode=fsFromMark, .delta=1, .writesize=2, .data="abcAB", .finalpos=5, .err=noErr},
		{.filesize=3, .initialpos=2, .mode=fsFromMark, .delta=1, .writesize=3, .data="abcABC", .finalpos=6, .err=noErr},
		{.filesize=3, .initialpos=2, .mode=fsFromMark, .delta=1, .writesize=4, .data="abcABCD", .finalpos=7, .err=noErr},
		{.filesize=3, .initialpos=2, .mode=fsFromMark, .delta=1, .writesize=5, .data="abcABCDE", .finalpos=8, .err=noErr},
		{.filesize=3, .initialpos=3, .mode=fsFromMark, .delta=-3, .writesize=0, .data="abc", .finalpos=0, .err=noErr},
		{.filesize=3, .initialpos=3, .mode=fsFromMark, .delta=-3, .writesize=1, .data="Abc", .finalpos=1, .err=noErr},
		{.filesize=3, .initialpos=3, .mode=fsFromMark, .delta=-3, .writesize=2, .data="ABc", .finalpos=2, .err=noErr},
		{.filesize=3, .initialpos=3, .mode=fsFromMark, .delta=-3, .writesize=3, .data="ABC", .finalpos=3, .err=noErr},
		{.filesize=3, .initialpos=3, .mode=fsFromMark, .delta=-3, .writesize=4, .data="ABCD", .finalpos=4, .err=noErr},
		{.filesize=3, .initialpos=3, .mode=fsFromMark, .delta=-3, .writesize=5, .data="ABCDE", .finalpos=5, .err=noErr},
		{.filesize=3, .initialpos=3, .mode=fsFromMark, .delta=-2, .writesize=0, .data="abc", .finalpos=1, .err=noErr},
		{.filesize=3, .initialpos=3, .mode=fsFromMark, .delta=-2, .writesize=1, .data="aAc", .finalpos=2, .err=noErr},
		{.filesize=3, .initialpos=3, .mode=fsFromMark, .delta=-2, .writesize=2, .data="aAB", .finalpos=3, .err=noErr},
		{.filesize=3, .initialpos=3, .mode=fsFromMark, .delta=-2, .writesize=3, .data="aABC", .finalpos=4, .err=noErr},
		{.filesize=3, .initialpos=3, .mode=fsFromMark, .delta=-2, .writesize=4, .data="aABCD", .finalpos=5, .err=noErr},
		{.filesize=3, .initialpos=3, .mode=fsFromMark, .delta=-2, .writesize=5, .data="aABCDE", .finalpos=6, .err=noErr},
		{.filesize=3, .initialpos=3, .mode=fsFromMark, .delta=-1, .writesize=0, .data="abc", .finalpos=2, .err=noErr},
		{.filesize=3, .initialpos=3, .mode=fsFromMark, .delta=-1, .writesize=1, .data="abA", .finalpos=3, .err=noErr},
		{.filesize=3, .initialpos=3, .mode=fsFromMark, .delta=-1, .writesize=2, .data="abAB", .finalpos=4, .err=noErr},
		{.filesize=3, .initialpos=3, .mode=fsFromMark, .delta=-1, .writesize=3, .data="abABC", .finalpos=5, .err=noErr},
		{.filesize=3, .initialpos=3, .mode=fsFromMark, .delta=-1, .writesize=4, .data="abABCD", .finalpos=6, .err=noErr},
		{.filesize=3, .initialpos=3, .mode=fsFromMark, .delta=-1, .writesize=5, .data="abABCDE", .finalpos=7, .err=noErr},
		{.filesize=3, .initialpos=3, .mode=fsFromMark, .delta=0, .writesize=0, .data="abc", .finalpos=3, .err=noErr},
		{.filesize=3, .initialpos=3, .mode=fsFromMark, .delta=0, .writesize=1, .data="abcA", .finalpos=4, .err=noErr},
		{.filesize=3, .initialpos=3, .mode=fsFromMark, .delta=0, .writesize=2, .data="abcAB", .finalpos=5, .err=noErr},
		{.filesize=3, .initialpos=3, .mode=fsFromMark, .delta=0, .writesize=3, .data="abcABC", .finalpos=6, .err=noErr},
		{.filesize=3, .initialpos=3, .mode=fsFromMark, .delta=0, .writesize=4, .data="abcABCD", .finalpos=7, .err=noErr},
		{.filesize=3, .initialpos=3, .mode=fsFromMark, .delta=0, .writesize=5, .data="abcABCDE", .finalpos=8, .err=noErr},
		{.filesize=4, .initialpos=0, .mode=fsFromMark, .delta=0, .writesize=0, .data="abcd", .finalpos=0, .err=noErr},
		{.filesize=4, .initialpos=0, .mode=fsFromMark, .delta=0, .writesize=1, .data="Abcd", .finalpos=1, .err=noErr},
		{.filesize=4, .initialpos=0, .mode=fsFromMark, .delta=0, .writesize=2, .data="ABcd", .finalpos=2, .err=noErr},
		{.filesize=4, .initialpos=0, .mode=fsFromMark, .delta=0, .writesize=3, .data="ABCd", .finalpos=3, .err=noErr},
		{.filesize=4, .initialpos=0, .mode=fsFromMark, .delta=0, .writesize=4, .data="ABCD", .finalpos=4, .err=noErr},
		{.filesize=4, .initialpos=0, .mode=fsFromMark, .delta=0, .writesize=5, .data="ABCDE", .finalpos=5, .err=noErr},
		{.filesize=4, .initialpos=0, .mode=fsFromMark, .delta=1, .writesize=0, .data="abcd", .finalpos=1, .err=noErr},
		{.filesize=4, .initialpos=0, .mode=fsFromMark, .delta=1, .writesize=1, .data="aAcd", .finalpos=2, .err=noErr},
		{.filesize=4, .initialpos=0, .mode=fsFromMark, .delta=1, .writesize=2, .data="aABd", .finalpos=3, .err=noErr},
		{.filesize=4, .initialpos=0, .mode=fsFromMark, .delta=1, .writesize=3, .data="aABC", .finalpos=4, .err=noErr},
		{.filesize=4, .initialpos=0, .mode=fsFromMark, .delta=1, .writesize=4, .data="aABCD", .finalpos=5, .err=noErr},
		{.filesize=4, .initialpos=0, .mode=fsFromMark, .delta=1, .writesize=5, .data="aABCDE", .finalpos=6, .err=noErr},
		{.filesize=4, .initialpos=0, .mode=fsFromMark, .delta=2, .writesize=0, .data="abcd", .finalpos=2, .err=noErr},
		{.filesize=4, .initialpos=0, .mode=fsFromMark, .delta=2, .writesize=1, .data="abAd", .finalpos=3, .err=noErr},
		{.filesize=4, .initialpos=0, .mode=fsFromMark, .delta=2, .writesize=2, .data="abAB", .finalpos=4, .err=noErr},
		{.filesize=4, .initialpos=0, .mode=fsFromMark, .delta=2, .writesize=3, .data="abABC", .finalpos=5, .err=noErr},
		{.filesize=4, .initialpos=0, .mode=fsFromMark, .delta=2, .writesize=4, .data="abABCD", .finalpos=6, .err=noErr},
		{.filesize=4, .initialpos=0, .mode=fsFromMark, .delta=2, .writesize=5, .data="abABCDE", .finalpos=7, .err=noErr},
		{.filesize=4, .initialpos=0, .mode=fsFromMark, .delta=3, .writesize=0, .data="abcd", .finalpos=3, .err=noErr},
		{.filesize=4, .initialpos=0, .mode=fsFromMark, .delta=3, .writesize=1, .data="abcA", .finalpos=4, .err=noErr},
		{.filesize=4, .initialpos=0, .mode=fsFromMark, .delta=3, .writesize=2, .data="abcAB", .finalpos=5, .err=noErr},
		{.filesize=4, .initialpos=0, .mode=fsFromMark, .delta=3, .writesize=3, .data="abcABC", .finalpos=6, .err=noErr},
		{.filesize=4, .initialpos=0, .mode=fsFromMark, .delta=3, .writesize=4, .data="abcABCD", .finalpos=7, .err=noErr},
		{.filesize=4, .initialpos=0, .mode=fsFromMark, .delta=3, .writesize=5, .data="abcABCDE", .finalpos=8, .err=noErr},
		{.filesize=4, .initialpos=0, .mode=fsFromMark, .delta=4, .writesize=0, .data="abcd", .finalpos=4, .err=noErr},
		{.filesize=4, .initialpos=0, .mode=fsFromMark, .delta=4, .writesize=1, .data="abcdA", .finalpos=5, .err=noErr},
		{.filesize=4, .initialpos=0, .mode=fsFromMark, .delta=4, .writesize=2, .data="abcdAB", .finalpos=6, .err=noErr},
		{.filesize=4, .initialpos=0, .mode=fsFromMark, .delta=4, .writesize=3, .data="abcdABC", .finalpos=7, .err=noErr},
		{.filesize=4, .initialpos=0, .mode=fsFromMark, .delta=4, .writesize=4, .data="abcdABCD", .finalpos=8, .err=noErr},
		{.filesize=4, .initialpos=0, .mode=fsFromMark, .delta=4, .writesize=5, .data="abcdABCDE", .finalpos=9, .err=noErr},
		{.filesize=4, .initialpos=1, .mode=fsFromMark, .delta=-1, .writesize=0, .data="abcd", .finalpos=0, .err=noErr},
		{.filesize=4, .initialpos=1, .mode=fsFromMark, .delta=-1, .writesize=1, .data="Abcd", .finalpos=1, .err=noErr},
		{.filesize=4, .initialpos=1, .mode=fsFromMark, .delta=-1, .writesize=2, .data="ABcd", .finalpos=2, .err=noErr},
		{.filesize=4, .initialpos=1, .mode=fsFromMark, .delta=-1, .writesize=3, .data="ABCd", .finalpos=3, .err=noErr},
		{.filesize=4, .initialpos=1, .mode=fsFromMark, .delta=-1, .writesize=4, .data="ABCD", .finalpos=4, .err=noErr},
		{.filesize=4, .initialpos=1, .mode=fsFromMark, .delta=-1, .writesize=5, .data="ABCDE", .finalpos=5, .err=noErr},
		{.filesize=4, .initialpos=1, .mode=fsFromMark, .delta=0, .writesize=0, .data="abcd", .finalpos=1, .err=noErr},
		{.filesize=4, .initialpos=1, .mode=fsFromMark, .delta=0, .writesize=1, .data="aAcd", .finalpos=2, .err=noErr},
		{.filesize=4, .initialpos=1, .mode=fsFromMark, .delta=0, .writesize=2, .data="aABd", .finalpos=3, .err=noErr},
		{.filesize=4, .initialpos=1, .mode=fsFromMark, .delta=0, .writesize=3, .data="aABC", .finalpos=4, .err=noErr},
		{.filesize=4, .initialpos=1, .mode=fsFromMark, .delta=0, .writesize=4, .data="aABCD", .finalpos=5, .err=noErr},
		{.filesize=4, .initialpos=1, .mode=fsFromMark, .delta=0, .writesize=5, .data="aABCDE", .finalpos=6, .err=noErr},
		{.filesize=4, .initialpos=1, .mode=fsFromMark, .delta=1, .writesize=0, .data="abcd", .finalpos=2, .err=noErr},
		{.filesize=4, .initialpos=1, .mode=fsFromMark, .delta=1, .writesize=1, .data="abAd", .finalpos=3, .err=noErr},
		{.filesize=4, .initialpos=1, .mode=fsFromMark, .delta=1, .writesize=2, .data="abAB", .finalpos=4, .err=noErr},
		{.filesize=4, .initialpos=1, .mode=fsFromMark, .delta=1, .writesize=3, .data="abABC", .finalpos=5, .err=noErr},
		{.filesize=4, .initialpos=1, .mode=fsFromMark, .delta=1, .writesize=4, .data="abABCD", .finalpos=6, .err=noErr},
		{.filesize=4, .initialpos=1, .mode=fsFromMark, .delta=1, .writesize=5, .data="abABCDE", .finalpos=7, .err=noErr},
		{.filesize=4, .initialpos=1, .mode=fsFromMark, .delta=2, .writesize=0, .data="abcd", .finalpos=3, .err=noErr},
		{.filesize=4, .initialpos=1, .mode=fsFromMark, .delta=2, .writesize=1, .data="abcA", .finalpos=4, .err=noErr},
		{.filesize=4, .initialpos=1, .mode=fsFromMark, .delta=2, .writesize=2, .data="abcAB", .finalpos=5, .err=noErr},
		{.filesize=4, .initialpos=1, .mode=fsFromMark, .delta=2, .writesize=3, .data="abcABC", .finalpos=6, .err=noErr},
		{.filesize=4, .initialpos=1, .mode=fsFromMark, .delta=2, .writesize=4, .data="abcABCD", .finalpos=7, .err=noErr},
		{.filesize=4, .initialpos=1, .mode=fsFromMark, .delta=2, .writesize=5, .data="abcABCDE", .finalpos=8, .err=noErr},
		{.filesize=4, .initialpos=1, .mode=fsFromMark, .delta=3, .writesize=0, .data="abcd", .finalpos=4, .err=noErr},
		{.filesize=4, .initialpos=1, .mode=fsFromMark, .delta=3, .writesize=1, .data="abcdA", .finalpos=5, .err=noErr},
		{.filesize=4, .initialpos=1, .mode=fsFromMark, .delta=3, .writesize=2, .data="abcdAB", .finalpos=6, .err=noErr},
		{.filesize=4, .initialpos=1, .mode=fsFromMark, .delta=3, .writesize=3, .data="abcdABC", .finalpos=7, .err=noErr},
		{.filesize=4, .initialpos=1, .mode=fsFromMark, .delta=3, .writesize=4, .data="abcdABCD", .finalpos=8, .err=noErr},
		{.filesize=4, .initialpos=1, .mode=fsFromMark, .delta=3, .writesize=5, .data="abcdABCDE", .finalpos=9, .err=noErr},
		{.filesize=4, .initialpos=2, .mode=fsFromMark, .delta=-2, .writesize=0, .data="abcd", .finalpos=0, .err=noErr},
		{.filesize=4, .initialpos=2, .mode=fsFromMark, .delta=-2, .writesize=1, .data="Abcd", .finalpos=1, .err=noErr},
		{.filesize=4, .initialpos=2, .mode=fsFromMark, .delta=-2, .writesize=2, .data="ABcd", .finalpos=2, .err=noErr},
		{.filesize=4, .initialpos=2, .mode=fsFromMark, .delta=-2, .writesize=3, .data="ABCd", .finalpos=3, .err=noErr},
		{.filesize=4, .initialpos=2, .mode=fsFromMark, .delta=-2, .writesize=4, .data="ABCD", .finalpos=4, .err=noErr},
		{.filesize=4, .initialpos=2, .mode=fsFromMark, .delta=-2, .writesize=5, .data="ABCDE", .finalpos=5, .err=noErr},
		{.filesize=4, .initialpos=2, .mode=fsFromMark, .delta=-1, .writesize=0, .data="abcd", .finalpos=1, .err=noErr},
		{.filesize=4, .initialpos=2, .mode=fsFromMark, .delta=-1, .writesize=1, .data="aAcd", .finalpos=2, .err=noErr},
		{.filesize=4, .initialpos=2, .mode=fsFromMark, .delta=-1, .writesize=2, .data="aABd", .finalpos=3, .err=noErr},
		{.filesize=4, .initialpos=2, .mode=fsFromMark, .delta=-1, .writesize=3, .data="aABC", .finalpos=4, .err=noErr},
		{.filesize=4, .initialpos=2, .mode=fsFromMark, .delta=-1, .writesize=4, .data="aABCD", .finalpos=5, .err=noErr},
		{.filesize=4, .initialpos=2, .mode=fsFromMark, .delta=-1, .writesize=5, .data="aABCDE", .finalpos=6, .err=noErr},
		{.filesize=4, .initialpos=2, .mode=fsFromMark, .delta=0, .writesize=0, .data="abcd", .finalpos=2, .err=noErr},
		{.filesize=4, .initialpos=2, .mode=fsFromMark, .delta=0, .writesize=1, .data="abAd", .finalpos=3, .err=noErr},
		{.filesize=4, .initialpos=2, .mode=fsFromMark, .delta=0, .writesize=2, .data="abAB", .finalpos=4, .err=noErr},
		{.filesize=4, .initialpos=2, .mode=fsFromMark, .delta=0, .writesize=3, .data="abABC", .finalpos=5, .err=noErr},
		{.filesize=4, .initialpos=2, .mode=fsFromMark, .delta=0, .writesize=4, .data="abABCD", .finalpos=6, .err=noErr},
		{.filesize=4, .initialpos=2, .mode=fsFromMark, .delta=0, .writesize=5, .data="abABCDE", .finalpos=7, .err=noErr},
		{.filesize=4, .initialpos=2, .mode=fsFromMark, .delta=1, .writesize=0, .data="abcd", .finalpos=3, .err=noErr},
		{.filesize=4, .initialpos=2, .mode=fsFromMark, .delta=1, .writesize=1, .data="abcA", .finalpos=4, .err=noErr},
		{.filesize=4, .initialpos=2, .mode=fsFromMark, .delta=1, .writesize=2, .data="abcAB", .finalpos=5, .err=noErr},
		{.filesize=4, .initialpos=2, .mode=fsFromMark, .delta=1, .writesize=3, .data="abcABC", .finalpos=6, .err=noErr},
		{.filesize=4, .initialpos=2, .mode=fsFromMark, .delta=1, .writesize=4, .data="abcABCD", .finalpos=7, .err=noErr},
		{.filesize=4, .initialpos=2, .mode=fsFromMark, .delta=1, .writesize=5, .data="abcABCDE", .finalpos=8, .err=noErr},
		{.filesize=4, .initialpos=2, .mode=fsFromMark, .delta=2, .writesize=0, .data="abcd", .finalpos=4, .err=noErr},
		{.filesize=4, .initialpos=2, .mode=fsFromMark, .delta=2, .writesize=1, .data="abcdA", .finalpos=5, .err=noErr},
		{.filesize=4, .initialpos=2, .mode=fsFromMark, .delta=2, .writesize=2, .data="abcdAB", .finalpos=6, .err=noErr},
		{.filesize=4, .initialpos=2, .mode=fsFromMark, .delta=2, .writesize=3, .data="abcdABC", .finalpos=7, .err=noErr},
		{.filesize=4, .initialpos=2, .mode=fsFromMark, .delta=2, .writesize=4, .data="abcdABCD", .finalpos=8, .err=noErr},
		{.filesize=4, .initialpos=2, .mode=fsFromMark, .delta=2, .writesize=5, .data="abcdABCDE", .finalpos=9, .err=noErr},
		{.filesize=4, .initialpos=3, .mode=fsFromMark, .delta=-3, .writesize=0, .data="abcd", .finalpos=0, .err=noErr},
		{.filesize=4, .initialpos=3, .mode=fsFromMark, .delta=-3, .writesize=1, .data="Abcd", .finalpos=1, .err=noErr},
		{.filesize=4, .initialpos=3, .mode=fsFromMark, .delta=-3, .writesize=2, .data="ABcd", .finalpos=2, .err=noErr},
		{.filesize=4, .initialpos=3, .mode=fsFromMark, .delta=-3, .writesize=3, .data="ABCd", .finalpos=3, .err=noErr},
		{.filesize=4, .initialpos=3, .mode=fsFromMark, .delta=-3, .writesize=4, .data="ABCD", .finalpos=4, .err=noErr},
		{.filesize=4, .initialpos=3, .mode=fsFromMark, .delta=-3, .writesize=5, .data="ABCDE", .finalpos=5, .err=noErr},
		{.filesize=4, .initialpos=3, .mode=fsFromMark, .delta=-2, .writesize=0, .data="abcd", .finalpos=1, .err=noErr},
		{.filesize=4, .initialpos=3, .mode=fsFromMark, .delta=-2, .writesize=1, .data="aAcd", .finalpos=2, .err=noErr},
		{.filesize=4, .initialpos=3, .mode=fsFromMark, .delta=-2, .writesize=2, .data="aABd", .finalpos=3, .err=noErr},
		{.filesize=4, .initialpos=3, .mode=fsFromMark, .delta=-2, .writesize=3, .data="aABC", .finalpos=4, .err=noErr},
		{.filesize=4, .initialpos=3, .mode=fsFromMark, .delta=-2, .writesize=4, .data="aABCD", .finalpos=5, .err=noErr},
		{.filesize=4, .initialpos=3, .mode=fsFromMark, .delta=-2, .writesize=5, .data="aABCDE", .finalpos=6, .err=noErr},
		{.filesize=4, .initialpos=3, .mode=fsFromMark, .delta=-1, .writesize=0, .data="abcd", .finalpos=2, .err=noErr},
		{.filesize=4, .initialpos=3, .mode=fsFromMark, .delta=-1, .writesize=1, .data="abAd", .finalpos=3, .err=noErr},
		{.filesize=4, .initialpos=3, .mode=fsFromMark, .delta=-1, .writesize=2, .data="abAB", .finalpos=4, .err=noErr},
		{.filesize=4, .initialpos=3, .mode=fsFromMark, .delta=-1, .writesize=3, .data="abABC", .finalpos=5, .err=noErr},
		{.filesize=4, .initialpos=3, .mode=fsFromMark, .delta=-1, .writesize=4, .data="abABCD", .finalpos=6, .err=noErr},
		{.filesize=4, .initialpos=3, .mode=fsFromMark, .delta=-1, .writesize=5, .data="abABCDE", .finalpos=7, .err=noErr},
		{.filesize=4, .initialpos=3, .mode=fsFromMark, .delta=0, .writesize=0, .data="abcd", .finalpos=3, .err=noErr},
		{.filesize=4, .initialpos=3, .mode=fsFromMark, .delta=0, .writesize=1, .data="abcA", .finalpos=4, .err=noErr},
		{.filesize=4, .initialpos=3, .mode=fsFromMark, .delta=0, .writesize=2, .data="abcAB", .finalpos=5, .err=noErr},
		{.filesize=4, .initialpos=3, .mode=fsFromMark, .delta=0, .writesize=3, .data="abcABC", .finalpos=6, .err=noErr},
		{.filesize=4, .initialpos=3, .mode=fsFromMark, .delta=0, .writesize=4, .data="abcABCD", .finalpos=7, .err=noErr},
		{.filesize=4, .initialpos=3, .mode=fsFromMark, .delta=0, .writesize=5, .data="abcABCDE", .finalpos=8, .err=noErr},
		{.filesize=4, .initialpos=3, .mode=fsFromMark, .delta=1, .writesize=0, .data="abcd", .finalpos=4, .err=noErr},
		{.filesize=4, .initialpos=3, .mode=fsFromMark, .delta=1, .writesize=1, .data="abcdA", .finalpos=5, .err=noErr},
		{.filesize=4, .initialpos=3, .mode=fsFromMark, .delta=1, .writesize=2, .data="abcdAB", .finalpos=6, .err=noErr},
		{.filesize=4, .initialpos=3, .mode=fsFromMark, .delta=1, .writesize=3, .data="abcdABC", .finalpos=7, .err=noErr},
		{.filesize=4, .initialpos=3, .mode=fsFromMark, .delta=1, .writesize=4, .data="abcdABCD", .finalpos=8, .err=noErr},
		{.filesize=4, .initialpos=3, .mode=fsFromMark, .delta=1, .writesize=5, .data="abcdABCDE", .finalpos=9, .err=noErr},
		{.filesize=4, .initialpos=4, .mode=fsFromMark, .delta=-4, .writesize=0, .data="abcd", .finalpos=0, .err=noErr},
		{.filesize=4, .initialpos=4, .mode=fsFromMark, .delta=-4, .writesize=1, .data="Abcd", .finalpos=1, .err=noErr},
		{.filesize=4, .initialpos=4, .mode=fsFromMark, .delta=-4, .writesize=2, .data="ABcd", .finalpos=2, .err=noErr},
		{.filesize=4, .initialpos=4, .mode=fsFromMark, .delta=-4, .writesize=3, .data="ABCd", .finalpos=3, .err=noErr},
		{.filesize=4, .initialpos=4, .mode=fsFromMark, .delta=-4, .writesize=4, .data="ABCD", .finalpos=4, .err=noErr},
		{.filesize=4, .initialpos=4, .mode=fsFromMark, .delta=-4, .writesize=5, .data="ABCDE", .finalpos=5, .err=noErr},
		{.filesize=4, .initialpos=4, .mode=fsFromMark, .delta=-3, .writesize=0, .data="abcd", .finalpos=1, .err=noErr},
		{.filesize=4, .initialpos=4, .mode=fsFromMark, .delta=-3, .writesize=1, .data="aAcd", .finalpos=2, .err=noErr},
		{.filesize=4, .initialpos=4, .mode=fsFromMark, .delta=-3, .writesize=2, .data="aABd", .finalpos=3, .err=noErr},
		{.filesize=4, .initialpos=4, .mode=fsFromMark, .delta=-3, .writesize=3, .data="aABC", .finalpos=4, .err=noErr},
		{.filesize=4, .initialpos=4, .mode=fsFromMark, .delta=-3, .writesize=4, .data="aABCD", .finalpos=5, .err=noErr},
		{.filesize=4, .initialpos=4, .mode=fsFromMark, .delta=-3, .writesize=5, .data="aABCDE", .finalpos=6, .err=noErr},
		{.filesize=4, .initialpos=4, .mode=fsFromMark, .delta=-2, .writesize=0, .data="abcd", .finalpos=2, .err=noErr},
		{.filesize=4, .initialpos=4, .mode=fsFromMark, .delta=-2, .writesize=1, .data="abAd", .finalpos=3, .err=noErr},
		{.filesize=4, .initialpos=4, .mode=fsFromMark, .delta=-2, .writesize=2, .data="abAB", .finalpos=4, .err=noErr},
		{.filesize=4, .initialpos=4, .mode=fsFromMark, .delta=-2, .writesize=3, .data="abABC", .finalpos=5, .err=noErr},
		{.filesize=4, .initialpos=4, .mode=fsFromMark, .delta=-2, .writesize=4, .data="abABCD", .finalpos=6, .err=noErr},
		{.filesize=4, .initialpos=4, .mode=fsFromMark, .delta=-2, .writesize=5, .data="abABCDE", .finalpos=7, .err=noErr},
		{.filesize=4, .initialpos=4, .mode=fsFromMark, .delta=-1, .writesize=0, .data="abcd", .finalpos=3, .err=noErr},
		{.filesize=4, .initialpos=4, .mode=fsFromMark, .delta=-1, .writesize=1, .data="abcA", .finalpos=4, .err=noErr},
		{.filesize=4, .initialpos=4, .mode=fsFromMark, .delta=-1, .writesize=2, .data="abcAB", .finalpos=5, .err=noErr},
		{.filesize=4, .initialpos=4, .mode=fsFromMark, .delta=-1, .writesize=3, .data="abcABC", .finalpos=6, .err=noErr},
		{.filesize=4, .initialpos=4, .mode=fsFromMark, .delta=-1, .writesize=4, .data="abcABCD", .finalpos=7, .err=noErr},
		{.filesize=4, .initialpos=4, .mode=fsFromMark, .delta=-1, .writesize=5, .data="abcABCDE", .finalpos=8, .err=noErr},
		{.filesize=4, .initialpos=4, .mode=fsFromMark, .delta=0, .writesize=0, .data="abcd", .finalpos=4, .err=noErr},
		{.filesize=4, .initialpos=4, .mode=fsFromMark, .delta=0, .writesize=1, .data="abcdA", .finalpos=5, .err=noErr},
		{.filesize=4, .initialpos=4, .mode=fsFromMark, .delta=0, .writesize=2, .data="abcdAB", .finalpos=6, .err=noErr},
		{.filesize=4, .initialpos=4, .mode=fsFromMark, .delta=0, .writesize=3, .data="abcdABC", .finalpos=7, .err=noErr},
		{.filesize=4, .initialpos=4, .mode=fsFromMark, .delta=0, .writesize=4, .data="abcdABCD", .finalpos=8, .err=noErr},
		{.filesize=4, .initialpos=4, .mode=fsFromMark, .delta=0, .writesize=5, .data="abcdABCDE", .finalpos=9, .err=noErr},
		{-1}
	};

	for (struct line *l=lines; l->filesize!=-1; l++) {
		short ref = MkScratchFileAlphabetic(l->filesize);

		// Pre-set the mark
		struct IOParam setuppb = {.ioRefNum=ref, .ioPosMode=fsFromStart, .ioPosOffset=l->initialpos};
		PBSetFPosSync((void *)&setuppb);
		long thepos = 99;
		GetFPos(ref, &thepos);
		if (thepos != l->initialpos) TAPBailOut("Could not pre-set mark, wanted %d got %d", l->initialpos, thepos);

		struct IOParam pb = {.ioRefNum=ref, .ioPosMode=l->mode, .ioPosOffset=l->delta, .ioReqCount=l->writesize, .ioActCount=99, .ioBuffer="ABCDEFGHIJ"};
		PBWriteSync((void *)&pb);

		// Where did the mark end up?
		long finalpos = 99;
		GetFPos(ref, &finalpos);
		if (finalpos != pb.ioPosOffset) TAPBailOut("FCB.fcbCrPs != PB.ioPosOffset");

		// What is the entire-file content now?
		char buf[20] = {};
		memset(buf, 0, sizeof buf);
		struct IOParam backpb = {.ioRefNum=ref, .ioPosMode=fsFromStart, .ioPosOffset=0, .ioReqCount=sizeof buf, .ioBuffer=buf};
		PBReadSync((void *)&backpb);
		if (backpb.ioResult != noErr && backpb.ioResult != eofErr) TAPBailOut("Readback failure");

		bool ok = finalpos == l->finalpos &&
			strlen(l->data) == backpb.ioActCount &&
			!strcmp(l->data, buf) &&
			pb.ioResult == l->err;

		TAPResult(ok, "Write(filesize=%d, initialpos=%d, mode=%s, delta=%d, writesize=%d) -> (data=\"%s\", finalpos=%d, err=%s)",
			l->filesize, l->initialpos, PosModeName(l->mode), l->delta, l->writesize, l->data, l->finalpos, ErrName(l->err));

		if (!ok) {
			printf("# got (data=\"%s\", finalpos=%d, err=%s)\n", buf, finalpos, ErrName(pb.ioResult));
		}

		FSClose(ref);
		FSDelete("\pscratch", 0);
	}
}
