#!/usr/bin/env lua

-- Borrowed from https://github.com/SolraBizna/mac_qfb_driver

local function linear2srgb(x)
   if x <= 0.0031308 then return x * 12.92
   else return 1.055 * math.pow(x, 1/2.4) - 0.055
   end
end

local function mac2linear(x)
   return math.pow(x, 1.8)
end

local function ntsc2linear(x)
   return math.pow(x, 2.2)
end

local function sgi2linear(x)
   return math.pow(x, 2.41)
end

local function pal2linear(x)
   return math.pow(x, 2.8)
end

local f = io.open("gammatables.c", "wb")

local function outtable(name, id, str, func)
   f:write("\t{\""..str.."\", {0, 0, 0, 1, 256, 8, {\n")
   for n=0,255 do
      if n % 8 == 0 then
         f:write("\t\t")
      end
      local basic_value = n / 255
      local corrected_value = math.floor(func(basic_value) * 255 + 0.5)
      assert(corrected_value >= 0 and corrected_value <= 255)
      f:write(("0x%02x,"):format(corrected_value))
      if n % 8 == 7 then
         f:write("\n")
      end
   end
   f:write("\t}}},\n")
end

f:write("// Auto-generated by gammatables-gen.lua -- do not edit!\n\n")
f:write("#include \"gammatables.h\"\n\n")
f:write("const struct builtinGamma builtinGamma[] = {\n")

outtable("_GammaTableMac", 128, "Mac Standard Gamma (1.8)", function(x) return linear2srgb(mac2linear(x)) end)
outtable("_GammaTableLinear", 129, "Linear Gamma (1.0)", function(x) return linear2srgb(x) end)
outtable("_GammaTableNTSC", 130, "NTSC/PC Gamma (2.2)", function(x) return linear2srgb(ntsc2linear(x)) end)
outtable("_GammaTableSGI", 131, "SGI Gamma (2.41)", function(x) return linear2srgb(sgi2linear(x)) end)
outtable("_GammaTablePAL", 132, "PAL/SECAM Gamma (2.8)", function(x) return linear2srgb(pal2linear(x)) end)

f:write("};\n\n")
f:write("const int builtinGammaCount = sizeof(builtinGamma)/sizeof(*builtinGamma);\n")
